network:
  version: 2
  renderer: networkd 
  ethernets:
    [interface]:
      dhcp4: [true/false]     
      dhcp6: [true/false]    
      addresses:
        - [ip_address]/[cidr_mask] 

      routes:
        - to: default
          via: [gateway_ip] 

      nameservers:
        addresses: [dns_server_1, dns_server_2]
